schedules:
- cron: "0 * * * *"
  branches:
    include:
    - master

trigger:
  batch: true
  branches:
    exclude:
    - "*"

jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      echo "running..."
    displayName: Install dependencies
