schedules:
- cron: "*/15 * * * *"
  always: true
  branches:
    include:
    - master

# trigger: none

jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      echo "running..."
    displayName: Install dependencies
