schedules:
- cron: "*/10 * * * *"
  branches:
    include:
    - master

# pr:
# - master

# trigger:
#   batch: true
#   branches:
#     include:
#     - "*"

jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      echo "running..."
    displayName: Install dependencies
